// <auto-generated />
using System;
using HotelMenagmentApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelMenagmentApi.Migrations
{
    [DbContext(typeof(HotelMenagmentContext))]
    [Migration("20200904182044_typedatechanged")]
    partial class typedatechanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelMenagmentApi.Models.Guest", b =>
                {
                    b.Property<int>("GuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Member_since")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuestID");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelMenagmentApi.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BreakfestIncluded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Check_in")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Check_out")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuestID")
                        .HasColumnType("int");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("GuestID");

                    b.HasIndex("RoomID");

                    b.ToTable("Reserevations");
                });

            modelBuilder.Entity("HotelMenagmentApi.Models.ReservationHistory", b =>
                {
                    b.Property<int>("ReservationHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GuestID")
                        .HasColumnType("int");

                    b.Property<string>("GuestName_History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount_History")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("check_in_History")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("check_out_History")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ReservationHistoryID");

                    b.HasIndex("GuestID");

                    b.HasIndex("RoomID");

                    b.ToTable("ReservationHistory");
                });

            modelBuilder.Entity("HotelMenagmentApi.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GuestID")
                        .HasColumnType("int");

                    b.Property<bool>("Is_cleaned")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_ocuppied")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("ReguralPrice")
                        .HasColumnType("int");

                    b.Property<bool>("Smoke")
                        .HasColumnType("bit");

                    b.Property<int>("nubmerbeds")
                        .HasColumnType("int");

                    b.HasKey("RoomID");

                    b.HasIndex("GuestID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelMenagmentApi.Models.Reservation", b =>
                {
                    b.HasOne("HotelMenagmentApi.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestID");

                    b.HasOne("HotelMenagmentApi.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID");
                });

            modelBuilder.Entity("HotelMenagmentApi.Models.ReservationHistory", b =>
                {
                    b.HasOne("HotelMenagmentApi.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestID");

                    b.HasOne("HotelMenagmentApi.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID");
                });

            modelBuilder.Entity("HotelMenagmentApi.Models.Room", b =>
                {
                    b.HasOne("HotelMenagmentApi.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestID");
                });
#pragma warning restore 612, 618
        }
    }
}
